<?php
  require('components/head.inc.php');
?>
<?php
  require('components/nav.inc.php');
?>
<?php
  include('components/mainCarousel.inc.php');
?>
<?php
  include('components/chooseYourTea.inc.php');
?>
<?php
  include('components/browseByCategory.inc.php')
?>
<?php
  include('components/topPicks.inc.php');
?>
<?php
  include('components/favTea.inc.php');
?>
<?php
  include('components/getInspired.inc.php');
?>
<?php
  include('components/sustainableTea.inc.php');
?>
<?php
  include('components/treatYourInbox.inc.php');
?>      
<?php
  include('components/footer.inc.php');
?>